repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: mixed-line-ending
        args: ["-f", "lf"]
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
        files: ^(FreeSimpleGUI.*)/.*\.py
