repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: mixed-line-ending
        args: ["-f", "lf"]
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: double-quote-string-fixer
        files: ^(FreeSimpleGUI(?:Qt|Web|Wx)?)/(?!Demo).*\.py
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        files: ^(FreeSimpleGUI(?:Qt|Web|Wx)?)/(?!Demo).*\.py
-   repo: https://github.com/psf/black
    rev: '24.4.2'
    hooks:
    -   id: black
        args:
            - "-S"
            - "-l"
            - "360"
        files: ^(FreeSimpleGUI(?:Qt|Web|Wx)?)/(?!Demo).*\.py

-   repo: https://github.com/pycqa/flake8
    rev: '7.0.0'  # pick a git hash / tag to point to
    hooks:
    -   id: flake8
        args:
          - "--ignore"
          - "E501,E704,E301,W503,E701,E722,E266,E203,E231"
        files: FreeSimpleGUI/FreeSimpleGUI.py
